<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ReportForge.Application\ReportForge.Application.csproj" />
    <ProjectReference Include="..\ReportForge.Infrastructure\ReportForge.Infrastructure.csproj" />
    <ProjectReference Include="..\ReportForge.Domain\ReportForge.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
